### ISSUE TITLE
Current error report

### ISSUE THREAD

**Issue by bortkiewicz** [DerpfacePython/Ways-to-NOT-make-money#119]
A summary of open issues/pull requests:
- [x] Attribute Error when buying Auto Clicker (#117)
- [ ] Only the last 8 digits of the money stored without -illions (#104)
- [x] Lotto buy button does not respond (#92)
- [x] Don't need Animation pictures now ( #115 )

( issues tagged with Enhancement aren't listed)

**Comment by DerpfacePython** [comment]
#92 and #115 are solved so far, I think (at least for mine).

**Comment by testitem** [comment]
#117 is fixed now.

**Comment by testitem** [comment]
hey.... why does upgrades LOWER my mps?

**Comment by DerpfacePython** [comment]
Wait... really? Take a screenshot (before and after).

**Comment by testitem** [comment]
BEFORE:
![img_2572](https://cloud.githubusercontent.com/assets/19212916/16170868/b6526cda-352e-11e6-817f-04a0282ee6dd.JPG)
)

AFTER:
![img_2573](https://cloud.githubusercontent.com/assets/19212916/16170869/c738dbce-352e-11e6-84a1-a1bf027f29b4.JPG)

**Comment by testitem** [comment]
see, @DerpfacePython ?

**Comment by testitem** [comment]
@DerpfacePython ??? How are we going to fix this?

**Comment by DerpfacePython** [comment]
TBH, we don't, we just change it to JS and everything will be fine.

**Comment by testitem** [comment]
Okay...
